# Generated by Django 3.2.6 on 2021-08-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210828_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverificationtoken',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='created',
        ),
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='updated',
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='created_at',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='updated_at',
            field=models.IntegerField(null=True),
        ),
    ]
