# Generated by Django 3.2.4 on 2021-06-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210612_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='module',
            name='content',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
