# Generated by Django 3.2.4 on 2021-06-12 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210612_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='module',
            name='content',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
    ]
