# Generated by Django 3.2.4 on 2021-06-16 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0007_rename_students_course_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
