# Generated by Django 3.2.4 on 2021-06-17 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0008_course_bookmarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='module',
            name='completed',
            field=models.ManyToManyField(blank=True, related_name='completed', to=settings.AUTH_USER_MODEL),
        ),
    ]
