# Generated by Django 3.2.4 on 2021-06-20 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_rating_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='reviews',
            new_name='review',
        ),
    ]
